# Accessing/Changing Specific row and Columbs

In [2]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
#get a specific elements[r,c]
a[1,5]

13

In [4]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
#get a specific column
a[:,1]

array([2, 9])

In [8]:
#Getting a little more fancy 
a[0,1:6:2]

array([2, 4, 6])

In [9]:
#Changing some value in array 
#I am changing the 13 value into 20
a[1,5] = 20 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [10]:
#Changing whole column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d Array examples

In [12]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
#get specific elemnts
b[3,1]

8