# Reorganizing Arrray

In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#Vertically stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
#Horizantal Stacking vector
h1 = np.array([[3,4,5],[3,2,1]])
h2 = np.array([[5,4],[2,1]])
np.hstack([h1,h2])


array([[3, 4, 5, 5, 4],
       [3, 2, 1, 2, 1]])

In [22]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
print(filedata)

[[ 1 23 43  2 22 12  4 32]
 [ 3  2  4  3  6  7 54  6]
 [ 5  6  7  5  4 32 23 55]]


In [23]:
filedata > 10

array([[False,  True,  True, False,  True,  True, False,  True],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False,  True,  True,  True]])