In [1]:
import numpy as np
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[2.0,8.9,3.4,2.1],[3.9,4.8,4.0,2.7]])
print(b)

[[2.  8.9 3.4 2.1]
 [3.9 4.8 4.  2.7]]


In [4]:
#dimensions of an array
a.ndim

1

In [5]:
#dimension of an array b
b.ndim

2

In [1]:
#finding the path of a file
pwd

'C:\\Users\\Miraj'

In [10]:
#get shape
b.shape

(2, 4)

In [18]:
#get type
a.dtype

dtype('int16')

In [19]:
a.itemsize

2