# Linear Algebra (Maths)

Matrix Multiplication

In [3]:
import numpy as np
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [4]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [5]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0