Initializing Different Types of Array

In [9]:
import numpy as np
a = np.zeros((2,3,3,2))
print(a)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [6]:
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [8]:
#Random decimal numbers creation
np.random.rand(4,3)

array([[0.3336415 , 0.68676789, 0.18626217],
       [0.81241611, 0.81026383, 0.80234717],
       [0.40117883, 0.77399222, 0.66569856],
       [0.23658907, 0.69884782, 0.99680171]])

In [10]:
#Random Integer Values
np.random.randint(7, size=(4,3))

array([[2, 1, 6],
       [4, 2, 2],
       [1, 3, 0],
       [0, 4, 6]])

In [16]:
#Repeat an array
c = np.array([[1,2,3]])
r1 = np.repeat(c,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
#Value of array a
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [23]:
#Values of array b
b = np.array([1,1,2,1])
print(b)

[1 1 2 1]


In [20]:
#Sum of a and b array
a + b

array([1, 3, 5, 5])

In [21]:
#Subtract of a and b array
a - b

array([1, 1, 1, 3])

In [24]:
#Divide of a and b array
a / b

array([1. , 2. , 1.5, 4. ])

In [25]:
#Multiply of a and b array
a * b

array([1, 2, 6, 4])

In [26]:
#power
a ** b

array([1, 2, 9, 4], dtype=int32)

In [33]:
#sin value of array a
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [34]:
#sin value of array b
np.sin(b)

array([0.84147098, 0.84147098, 0.90929743, 0.84147098])